name: DXL memberships module pull request workflow

on:
    push:
        branches:
            - staging

jobs:
    pull-request:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Creating pull request
              run: echo "Creating pull request for staging branch"
            
            - name: Pull request staging - master
              uses: Poorva17/create-pr-action@v2.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                HEAD_BRANCH: staging
                BASE_BRANCH: master
                PR_TITLE: "staging - master: ${{ github.event.head_commit.message }}"