name: Deploy to Simply.com

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install sshpass

    - name: Create SSH Key
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        cp ~/.ssh/id_rsa ~/.ssh/id_rsa.pem
    
    - name: Deploy to Simply.com
      run: |  
        sshpass -p ${{secrets.SSH_PASSWORD}} ssh -oStrictHostKeyChecking=no ${{secrets.SSH_USERNAME}}@${{secrets.sSSH_HOSTNAME}} "cd staging/wp-content/plugins/dxl-memberships && git pull"